# Deploy grafana + influxdb + mongodb
version: '3.8'
services:
  mongo:
    image: mongo:4.4.4-bionic
    container_name: mongodb
    ports:
      - 27017:27017
    restart: always
  influx:
    image: influxdb:1.8.4-alpine
    container_name: influxdb
    volumes:
      - /srv/docker/influxdb/data:/var/lib/influxdb
      - ./influx/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    ports:
      - 8086:8086
      - 8088:8088
    restart: always
  grafana:
    build: ./grafana
    container_name: grafana
    ports:
      - 3001:3000
    restart: always
